### ISSUE TITLE
Правило для URL

### ISSUE THREAD

**Issue by tonal** [apicrafter/metacrafter#2]
Можно ли добавить правило для нахождения URL-ов?
Вроде в **pyparsing** есть удобное правило `pyparsing.pyparsing_common.url`, но неясно как его добавить.

**Comment by ivbeg** [comment]
@tonal конечно можно, фишка в том что можно создавать свои правила, а путь к правилам настраивать. Конкретно url'ы валидирует validators.url функция из пакета validators. Я добавил референсную версию правил вот тут https://github.com/apicrafter/metacrafter/blob/main/rules/common/commonurl.yaml , но вообще Вы можете создать любое/любые свои правила, главное чтобы функция была вызываема и библиотека её доступна через import
